on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

name: Sync data to R2
jobs:
  copy-to-r2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "pypi-data/toolchain"
          fileName: "pypi-data-toolchain.tar.gz"
          extract: true
          latest: true
          out-file-path: "toolchain/"

      - name: Generate token
        id: generate_token
        uses: pypi-data/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get current date
        id: current-date
        run: |
          echo "date=$(date +%F)" >> "$GITHUB_OUTPUT"

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .cache/data.json
          key: data-${{ steps.current-date.outputs.date }}

      - env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        name: Build data
        run: |
          mkdir -p ${{ github.workspace }}/.cache/

          ${{ github.workspace }}/toolchain/pypi-data-toolchain static-site \
            --content-directory ${{ github.workspace }}/public/data/ \
            --reload-from ${{ github.workspace }}/.cache/data.json

      - name: Install deps
        run: |
          npm install

      - name: Build index
        run: npm run build-index

      - name: Sync to R2
        run: |
          aws s3 sync --size-only ${{ github.workspace }}/public/data/ s3://pypi-data/data/ \
            --region=auto \
            --endpoint-url ${{secrets.R2_ENDPOINT}} \
            --content-encoding=gzip \
            --only-show-errors
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_KEY }}
